# 에러 메세지 (errors.properties) 위치
spring:
  messages:
    basename: errors
  datasource:
    url: jdbc:mariadb://localhost:3306/skillExchange
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root1234

#  sql:
#    init:
#      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
#    defer-datasource-initialization: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: kimmin7932@gmail.com
    password: zcobonksycfssphi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 80

